### CONFIGURATION ###
# THEME - utilizes jekyll cayman (https://github.com/pages-themes/cayman) 
theme: jekyll-theme-cayman
title: Michael Lorenz Portfolio
description: About me as a software developer and my projects.
