### CONFIGURATION ###
# THEME - utilizes jekyll cayman (https://github.com/pages-themes/cayman) 
theme: jekyll-theme-cayman
title: [Michael Lorenz Portfolio]
description: [Learn more about me as a software developer and my projects.]
