### CONFIGURATION ###
# THEME - utilizes jekyll cayman (https://github.com/pages-themes/cayman) 
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Michael Lorenz Portfolio
description: [Learn more about me as a software developer and my projects.]

navbar-links:
  linkedin-title: "LinkedIn"
  linkedin-url: https://linkedin.com/in/michaellorenz
  github-title: "GitHub"
  github-url: https://github.com/Halfwitz
