### CONFIGURATION ###
# THEME - utilizes jekyll cayman (https://github.com/pages-themes/cayman) 
theme: jekyll-theme-cayman
title: [Michael Lorenz Portfolio]
description: [Learn more about me as a software developer and my projects.]
navbar-links:
  - title: "LinkedIn"
    url: "https://linkedin.com/in/michaellorenz"
  - title: "GitHub"
    url: "https://github.com/Halfwitz"
